source 'git@git.2dfire.net:ios/cocoapods-spec.git'
platform :ios, '8.0'

#use_frameworks!
#
#plugin 'cocoapods-tdfire-binary'
#
#tdfire_use_binary!
tdfire_use_source_pods ['TDFNetworkEnvironmentSwitcher']

target 'TDFDataDrivenKit_Example' do
  pod 'TDFDataDrivenKit', :path => '../'
  
  pod 'TDFNetworkEnvironmentSwitcher'
  pod 'TDFHttpProxy'
  pod 'TDFLoginAssistant/Login'
  pod 'TDFBossBaseInfoDefaults'
  pod 'TDFScreenDebugger'

  target 'TDFDataDrivenKit_Tests' do
    inherit! :search_paths

    
  end
end


# 三方库设置 inhibit_warnings = true
pre_install do |installer|
  installer.analysis_result.specs_by_target.each_key do |target_definition|
    installer.analysis_result.specifications.each do |spec|
      source = spec.attributes_hash['source']
      source &&= source['git']
      next unless source && source.include?('cocoapods-repos')

      targets = (Array(target_definition) + target_definition.children)
      targets.each do |target|
        target.set_inhibit_warnings_for_pod(spec.root.name, true)
      end
    end
  end
end
